language: c
sudo: false
notifications:
  irc: "irc.freenode.net#haskell-raaz"
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - hlint
      - cabal-install-1.18
      - cabal-install-1.22
      - ghc-7.8.4
      - ghc-7.10.3

fast_finish: true
# To notify immediately about it when a job of a build fails.
env:
  - STACKVER=lts-2   GHCVER=7.8.4 CABALVER=1.18
  - STACKVER=lts-4   GHCVER=7.10.3 CABALVER=1.22
  - STACKVER=nightly GHCVER=7.10.3 CABALVER=1.22
  - HLINT="yes"

matrix:
  allow_failures:
    - env: HLINT="yes"
    - env: STACKVER=nightly

before_install:
 - if [ "$HLINT" == "yes" ]; then
      hlint "--ignore=Parse error" Raaz;
      exit $?;
   fi
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - if [ "$STACKVER" != "" ]; then
      echo getting the stackage cabal.config;
      wget "https://www.stackage.org/$STACKVER/cabal.config";
   fi
install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist   # tests that a source-distribution can be generated
  - cabal install --force-reinstalls dist/*-*.tar.gz

  # - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
  #  (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - x-merge-packages
