notifications:
  irc: "irc.freenode.net#haskell-raaz"
env:
  # Variables.
  # 1. GHC_VERSION: The version of ghc to build against. If not set
  #    the default version of haskell on travis build system in used.
  #
  # 2. CABAL_VERSION: The version of cabal install command to use. If
  #    not set the default version available is used.
  #
  # 3. PARALLEL_BUILDS: Whether the version of cabal install supports
  #    parallel builds. Set it to "yes" if the version of cabal
  #    install supports parallel builds.
  #
  # 4. PACKAGE_CONSTRAINTS: The constraints to put on packages.
  #
  # 5. HASKELL_PLATFORM: You can build against a give platform. The
  #    corresponding makefile:
  #    ./platform/${HASKELL_PLATFORM}/Makefile.configure should
  #    exist. The platform makefile should usually set the GHC_VERSION
  #    and PACKAGE_CONSTRAINTS
  #
  # 6. ADDITIONAL_CONSTRAINTS: Set additional constraints on certain
  #    problematic packages.
  global:
    - ADDITIONAL_CONSTRAINTS=
    - PARALLEL_BUILDS="yes"
  matrix:
    - GHC_VERSION=7.8.3 CABAL_VERSION=1.20
    - HASKELL_PLATFORM=2013.2.0.0 GHC_VERSION=7.6.3 CABAL_VERSION=1.20
    - HASKELL_PLATFORM=2012.4.0.0 GHC_VERSION=7.4.2 CABAL_VERSION=1.20
    - HASKELL_PLATFORM=2012.2.0.0 GHC_VERSION=7.4.1 CABAL_VERSION=1.20
before_install:
  - echo `uname -a`
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - if [ "$GHC_VERSION" == "" ]; then
      travis_retry sudo apt-get install ghc happy haddock;
    else
      travis_retry sudo apt-get install ghc-$GHC_VERSION happy haddock;
      export PATH=/opt/ghc/$GHC_VERSION/bin:$PATH;
    fi
  - if [ "$CABAL_VERSION" == "" ]; then
      travis_retry sudo apt-get install cabal-install;
      cabal update;
    else
      travis_retry sudo apt-get install cabal-install-$CABAL_VERSION;
      export PATH=/opt/cabal/$CABAL_VERSION/bin:$PATH;
      cabal-$CABAL_VERSION update;
    fi
  - ghc --version
  - cabal --version
  - echo HASKELL_PLATFORM=${HASKELL_PLATFORM}
  - echo PARALLEL_BUILDS=${PARALLEL_BUILDS}
  - ghc -o travis scripts/travis-build.hs
install: "make install"
script: "echo tests already run."
branches:
  only:
    - master
    - x-travis
    - x-length
