language: haskell
env: INSTALL_OPTS="-O0 -enable-documentation --enable-tests --force-reinstall"
install: "make install INSTALL_OPTS
script: "make travis-tests"
branches:
  only:
    - master
    - x-merge
    - x-ssh
    - x-primitives
    - x-hash-sha
