language: c
sudo: false
os:
  - linux  # Build for linux systems.
  - osx    # Build for osx systems.

notifications:
  irc: "irc.freenode.net#haskell-raaz"
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - hlint
      - cabal-install-1.18
      - cabal-install-1.22
      - cabal-install-head
      - ghc-7.8.4
      - ghc-7.10.2
      - ghc-7.10.3
      - ghc-head

# Setting up caches
before-cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

fast_finish: true
# # To notify immediately about it when a job of a build fails.
# env:
#   - STACKVER=lts-2   GHCVER=7.8.4 CABALVER=1.18
#   - STACKVER=lts-3   GHCVER=7.10.2 CABALVER=1.22
#   - STACKVER=lts-4   GHCVER=7.10.3 CABALVER=1.22
#   - STACKVER=lts-5   GHCVER=7.10.3 CABALVER=1.22
#   - GHCVER=head CABALVER=head # Build against haskell head version.
#   - HLINT="yes"

matrix:
  include:
    - os: linux
      env:
        - STACKVER=lts-2   GHCVER=7.8.4 CABALVER=1.18
        - STACKVER=lts-3   GHCVER=7.10.2 CABALVER=1.22
        - STACKVER=lts-4   GHCVER=7.10.3 CABALVER=1.22
        - STACKVER=lts-5   GHCVER=7.10.3 CABALVER=1.22
        - GHCVER=head CABALVER=head # Build against haskell head version.
        - HLINT="yes"
    - os: osx
  allow_failures:
    - env: HLINT="yes"
    - env: GHCVER=head CABALVER=head
    - os: osx
before_install:
 - if [ "$HLINT" == "yes" ]; then
      hlint "--ignore=Parse error" Raaz;
      exit $?;
   fi
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - if [ "$STACKVER" != "" ]; then
      echo getting the stackage cabal.config;
      wget "https://www.stackage.org/$STACKVER/cabal.config";
   fi
install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist   # tests that a source-distribution can be generated
  - cabal install --force-reinstalls dist/*-*.tar.gz

  # - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
  #  (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - x-merge-packages
