language: c
sudo: false
notifications:
  irc: "irc.freenode.net#haskell-raaz"

# Setting up caches
before-cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/.stack
    - .stack-work

fast_finish: true

matrix:
  include:
    #
    # Linux builds
    #
    # Most recent LTS for 7.8.4 series.
    # Stackage LTS-2, with 7.8.4 and cabal version-1.18
    #
    # Build for Debian-8

    - os: linux
      env: HVR_COLLECTION=debian-8 GHCVER=7.6.3 CABALVER=1.20
      addons:
        apt: {packages: [ghc-7.6.3, cabal-install-1.20], sources:  [hvr-ghc] }

    - os: linux
      env: STACK="yes"
      addons:
        apt: { packages: [stack], sources: [fpcomplete-precise] }

    - os: linux
      env: STACK="yes" RESOLVER="--resolver=lts"
      addons:
          apt: { packages: [stack], sources: [fpcomplete-precise] }

    - os: linux
      env: STACK="yes" RESOLVER="--resolver=nighty"
      addons:
          apt: { packages: [stack], sources: [fpcomplete-precise] }
    #
    # Build against GHC-Head
    #

    - os: linux
      env: GHCVER=head CABALVER=head
      addons:
        apt:
          packages: [ghc-head, cabal-install-head]
          sources:  [hvr-ghc]

    - os: linux
      env: HLINT="yes"
      addons:
        apt: { packages: [hlint] }

    # Other builds
    - os: osx

  allow_failures:
    - env: GHCVER=head CABALVER=head
    - env: STACK="yes" RESOLVER="--resolver=nighty"
    - env: HLINT="yes"
before_install:
 - if [ "$HLINT" == "yes" ]; then
      hlint "--ignore=Parse error" Raaz;
      exit $?;
   fi
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

 - if [ "$STACK" != "" ]; then
      export BUILDCMD="stack $RESOLVER";
   else
      export BUILDCMD="cabal";
   fi

 - if [ "$HVR_COLLECTION" != "" ]; then
      wget https://raw.githubusercontent.com/hvr/multi-ghc-travis/master/collections/cabal.project."$HVR_COLLECTION" -O cabal.config ;
   fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghc cabal-install; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew info ghc cabal-install; fi

install:
 - $BUILDCMD --version
 - if [ "$BUILDCMD" == "cabal" ]; then
      travis_retry cabal update;
      cabal install --only-dependencies --enable-tests --enable-benchmarks;
   else
      $BUILDCMD --dependencies-only --test --bench;
   fi
script:
  - if [ "$BUILDCMD" == "cabal" ]; then
      cabal configure --only-dependencies --enable-tests --enable-benchmarks;
    fi

  - $BUILDCMD build
  - $BUILDCMD test

  - if [ "$BUILDCMD" == "cabal" ]; then cabal check; fi
  - if [ "$BUILDCMD" == "cabal" ]; then cabal sdist; fi
  - if [ "$BUILDCMD" == "cabal" ]; then
       cabal install --force-reinstalls dist/*-*.tar.gz;
    fi

after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - release-0.0.2
