env:
  - GHC_VERSION=7.4.2 CABAL_VERSION=1.18
  - GHC_VERSION=7.6.3 CABAL_VERSION=1.18

before_install: "make travis-before-install"
install: "make install"
script: "make  tests"

branches:
  only:
    - master
    - x-travis