language: c
sudo: false
notifications:
  irc: "irc.freenode.net#haskell-raaz"

addons: { apt: { sources: [hvr-ghc] }}

matrix:
  include:
    - env: STACKVER=lts-2.13 GHCVER=7.8.4 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4]}}
    - env: HLINT="yes"
      addons: {apt: {packages: [hlint]}}

matrix:
  # To notify immediately about it when a job of a build fails.
  fast_finish: true
  allow_failures:
    - env: HLINT="yes"

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - if [ "$STACKVER" != "" ]; then
      wget "https://www.stackage.org/$STACKVER/cabal.config"
   fi

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist   # tests that a source-distribution can be generated
  - cabal install --force-reinstalls dist/*-*.tar.gz

  # - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
  #  (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - x-merge-packages
