notifications:
  irc: "irc.freenode.net#haskell-raaz"
env:
  # Variables.
  # 1. GHC_VERSION: The version of ghc to build against. If not set
  #    the default version of haskell on travis build system in used.
  #
  # 2. CABAL_VERSION: The version of cabal install command to use. If
  #    not set the default version available is used.
  #
  # 3. PARALLEL_BUILDS: Whether the version of cabal install supports
  #    parallel builds. Set it to "yes" if the version of cabal
  #    install supports parallel builds.
  #
  # 4. PACKAGE_CONSTRAINTS: The constraints to put on packages.
  #
  # 5. HASKELL_PLATFORM: You can build against a give platform. The
  #    corresponding makefile:
  #    ./platform/${HASKELL_PLATFORM}/Makefile.configure should
  #    exist. The platform makefile should usually set the GHC_VERSION
  #    and PACKAGE_CONSTRAINTS
  #
  # 6. ADDITIONAL_CONSTRAINTS: Set additional constraints on certain
  #    problematic packages.
  global:
    - ADDITIONAL_CONSTRAINTS=
  matrix:
    - GHC_VERSION=7.8.3 CABAL_VERSION=1.20 PARALLEL_BUILDS="yes"
    - HASKELL_PLATFORM=2013.2.0.0 CABAL_VERSION=1.20 PARALLEL_BUILDS="yes"
    - HASKELL_PLATFORM=2012.4.0.0 CABAL_VERSION=1.20 PARALLEL_BUILDS="yes"
    - HASKELL_PLATFORM=2012.2.0.0 CABAL_VERSION=1.20 PARALLEL_BUILDS="yes"
before_install:
  - "make travis-before-install"
  - "make echo-variables"
install: "make install"
script: "echo tests already run."
branches:
  only:
    - master
    - x-travis
    - x-length
