language: haskell
install: "make install INSTALL_OPTS='-O0 --enable-documentation --enable-tests'"
script: "make travis-tests"
branches:
  only:
    - master
    - x-merge
    - x-ssh
    - x-primitives
    - x-hash-sha
