# This is the stack file used raaz package. Its flag settings are
# optimisitc and you may need to disable some to install on you
# machine.
packages:
- '.'
resolver: lts-6.9

flags:
  raaz:
    vector128: true
    vector256: true
    vector512: true
    avx2: true